[workspace]
members = [
    "crates/winsp-core",
    "crates/winsp-indexer",
    "crates/winsp-app",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["WinSP Contributors"]
license = "MIT"
repository = "https://gitlab.com/winsp/winsp"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
