[package]
name = "winsp-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
winsp-service = { path = "../service" }
winsp-windows = { path = "../windows" }

[dev-dependencies]
winsp-service = { path = "../service", features = ["test-support"] }
winsp-windows = { path = "../windows", features = ["test-support"] }
