[package]
name = "winsp-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "winsp"
path = "src/main.rs"

[dependencies]
cfg-if = "1"
winsp-core = { path = "../core" }
winsp-windows = { path = "../windows" }

[build-dependencies]
embed-resource = "3"

[target.'cfg(windows)'.dependencies]
mimalloc = "0.1.52"
rmp-serde = "1.3"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
winsp-windows = { path = "../windows", features = ["test-support"] }
tempfile = "3.27.0"

