[package]
name = "winsp-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "winsp"
path = "src/main.rs"

[dependencies]
winsp-core = { path = "../core" }
winsp-windows = { path = "../windows" }

[build-dependencies]
embed-resource = "3"

[target.'cfg(windows)'.dependencies]
mimalloc = "0.1.52"

[target.'cfg(windows)'.dev-dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
] }

