[package]
name = "winsp-windows"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[features]
test-support = []

[dependencies]
lnk = "0.6"
lru = "0.18"
notify-debouncer-mini = "0.7.0"
walkdir = "2.5.0"
winsp-core = { path = "../core" }

[dev-dependencies]
tempfile = "3.27.0"

[target.'cfg(windows)'.dependencies]
num_enum = "0.7"
windows-registry = "0.6"
windows = { version = "0.62", features = [
    "ApplicationModel",
    "ApplicationModel_DataTransfer",
    "Data_Xml_Dom",
    "UI_Notifications",
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Storage_FileSystem",
    "Win32_Storage_Packaging_Appx",
] }

