[package]
name = "winsp-plugins"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
walkdir = "2.5.0"
winsp-core = { path = "../core" }

[target.'cfg(windows)'.dependencies]
winsp-windows = { path = "../windows" }
windows = { version = "0.62", features = [
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_UI_Shell",
] }

[dev-dependencies]
tempfile = "3.27.0"
