[package]
name = "winsp-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
compact_str = "0.10"
logos = "0.16"
nucleo-matcher = "0.3"

[dev-dependencies]
criterion = { version = "5.0.1", package = "codspeed-criterion-compat", features = ["html_reports"] }
trybuild = "1"

[[bench]]
name = "search"
harness = false

[[bench]]
name = "calculator"
harness = false

[[bench]]
name = "indexing"
harness = false

[[test]]
name = "compile_fail"
path = "tests/compile_fail/mod.rs"
