name: Lint

on:
  push:
    branches: [main]
    paths: [".github/workflows/**", ".github/actions/**", "scripts/**"]
  pull_request:
    paths: [".github/workflows/**", ".github/actions/**", "scripts/**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl -s https://raw.githubusercontent.com/rhysd/actionlint/v1.7.12/scripts/download-actionlint.bash)
        shell: bash

      - name: Check workflow files
        run: ${STEPS_GET_ACTIONLINT_OUTPUTS_EXECUTABLE} -color
        env:
          STEPS_GET_ACTIONLINT_OUTPUTS_EXECUTABLE: ${{ steps.get_actionlint.outputs.executable }}

  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install ruff
        run: curl -LsSf https://astral.sh/ruff/0.16.5/install.sh | sh

      - run: ruff check scripts/
